name: Run Python App on Windows

# Trigger the workflow on push or manual dispatch
on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner

    steps:
      - name: Checkout Code  # Step 1: Fetch the repository code
        uses: actions/checkout@v3

      - name: Set Up Python  # Step 2: Set up Python on Windows
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Specify the Python version

      - name: Install Dependencies  # Step 3: Install Python dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run Application  # Step 4: Run your Python app
        run: |
          python app.py

